# fly.toml
app = "movie-time"  # Change this to your Fly.io app name

primary_region = "ams"  # or choose the region closest to you (e.g., ams, fra, lhr, iad)

[build]
builder = "heroku/buildpacks:20"
buildpacks = ["heroku/nodejs"]

[env]
NODE_ENV = "production"

[deploy]
release_command = "npm install"

[experimental]
auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
